/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LinksRouteImport } from './routes/links'
import { Route as OcasioesRouteImport } from './routes/ocasioes'
import { Route as ConfirmarEntregaOrderNumberRouteImport } from './routes/confirmar-entrega.$orderNumber'
import { Route as PedidoOrderNumberRouteImport } from './routes/pedido.$orderNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const OcasioesRoute = OcasioesRouteImport.update({
  id: '/ocasioes',
  path: '/ocasioes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEntregaOrderNumberRoute =
  ConfirmarEntregaOrderNumberRouteImport.update({
    id: '/confirmar-entrega/$orderNumber',
    path: '/confirmar-entrega/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const PedidoOrderNumberRoute = PedidoOrderNumberRouteImport.update({
  id: '/pedido/$orderNumber',
  path: '/pedido/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/links': typeof LinksRoute
  '/ocasioes': typeof OcasioesRoute
  '/confirmar-entrega/$orderNumber': typeof ConfirmarEntregaOrderNumberRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/links': typeof LinksRoute
  '/ocasioes': typeof OcasioesRoute
  '/confirmar-entrega/$orderNumber': typeof ConfirmarEntregaOrderNumberRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/links': typeof LinksRoute
  '/ocasioes': typeof OcasioesRoute
  '/confirmar-entrega/$orderNumber': typeof ConfirmarEntregaOrderNumberRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/links'
    | '/ocasioes'
    | '/confirmar-entrega/$orderNumber'
    | '/pedido/$orderNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/links'
    | '/ocasioes'
    | '/confirmar-entrega/$orderNumber'
    | '/pedido/$orderNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/links'
    | '/ocasioes'
    | '/confirmar-entrega/$orderNumber'
    | '/pedido/$orderNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  LinksRoute: typeof LinksRoute
  OcasioesRoute: typeof OcasioesRoute
  ConfirmarEntregaOrderNumberRoute: typeof ConfirmarEntregaOrderNumberRoute
  PedidoOrderNumberRoute: typeof PedidoOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocasioes': {
      id: '/ocasioes'
      path: '/ocasioes'
      fullPath: '/ocasioes'
      preLoaderRoute: typeof OcasioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-entrega/$orderNumber': {
      id: '/confirmar-entrega/$orderNumber'
      path: '/confirmar-entrega/$orderNumber'
      fullPath: '/confirmar-entrega/$orderNumber'
      preLoaderRoute: typeof ConfirmarEntregaOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderNumber': {
      id: '/pedido/$orderNumber'
      path: '/pedido/$orderNumber'
      fullPath: '/pedido/$orderNumber'
      preLoaderRoute: typeof PedidoOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  LinksRoute: LinksRoute,
  OcasioesRoute: OcasioesRoute,
  ConfirmarEntregaOrderNumberRoute: ConfirmarEntregaOrderNumberRoute,
  PedidoOrderNumberRoute: PedidoOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
